name: R-CMD-check

on:
  push: {branches: [main, master]}
  pull_request: {branches: [main, master]}

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        r: ['release']

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r }}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: ai
          extra-packages: |
            any::rcmdcheck
            any::BiocManager
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          working-directory: ai
          upload-snapshots: true
